In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('cyclistic_cleaned.csv')

In [4]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,month,hour
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,13.957950,Tuesday,January,17
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,5.072400,Saturday,January,15
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,11.591667,Thursday,January,15
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,3.570550,Thursday,January,8
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,2.573817,Thursday,January,8

In [7]:
#calculating avg ride length for each rider type

df.groupby('member_casual')['ride_length'].mean()

member_casual
casual    22.546292
member    12.440265
Name: ride_length, dtype: float64

In [10]:
#total number of rides by each user type

df['member_casual'].value_counts()

member_casual
member    2351501
casual    1310155
Name: count, dtype: int64

In [40]:
# Define correct order of days of week instead of alphabetical (default)

day_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

df['day_of_week'] = pd.Categorical(df['day_of_week'], categories = day_order)

#Define correct order of month

month_order = ['January','February','March','April','May','June','July','September','October','November','December']

df['month'] = pd.Categorical(df['month'], categories = month_order)

In [41]:
#count rides by day of week and rider type

rides_by_day = df.groupby(['day_of_week', 'member_casual']).size()

rides_by_day.unstack()

C:\Users\laksh\AppData\Local\Temp\ipykernel_20236\279633383.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  rides_by_day = df.groupby(['day_of_week', 'member_casual']).size()

member_casual  casual  member
day_of_week
Monday         153433  345890
Tuesday        147447  380645
Wednesday      141774  367926
Thursday       164907  379700
Friday         208680  345561
Saturday       272547  283056
Sunday         221367  248723

In [42]:
#calculate avg ride length for each day and rider type

avg_length_day = df.groupby(['day_of_week','member_casual'])['ride_length'].mean()

avg_length_day.unstack()

C:\Users\laksh\AppData\Local\Temp\ipykernel_20236\998754019.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_length_day = df.groupby(['day_of_week','member_casual'])['ride_length'].mean()

member_casual     casual     member
day_of_week
Monday         22.133065  11.959795
Tuesday        19.998732  12.102616
Wednesday      18.418570  11.840162
Thursday       19.859002  11.927754
Friday         22.226718  12.408750
Saturday       25.338529  13.720730
Sunday         26.038509  13.881852

In [43]:
#count rides by month and rider type

rides_by_month = df.groupby(['month', 'member_casual']).size()

rides_by_month.unstack()

C:\Users\laksh\AppData\Local\Temp\ipykernel_20236\4083402659.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  rides_by_month = df.groupby(['month', 'member_casual']).size()

member_casual  casual  member
month
January         16946   83657
February        19481   89410
March           61055  147081
April           76328  180627
May            124488  213635
June           191136  251486
July           206471  283138
September      170635  292844
October        142188  271980
November        63620  169376
December        18660   76501

In [47]:
#calculate avg ride length by rider type and bike type

bike_usage = df.groupby(['rideable_type','member_casual'])['ride_length'].mean()

bike_usage.unstack()

member_casual     casual     member
rideable_type
classic_bike   29.315440  13.656662
electric_bike  15.505865  11.000930

In [45]:
#count rides by hour and rider type

rides_by_hour = df.groupby(['hour','member_casual']).size()

rides_by_hour.unstack()

member_casual  casual  member
hour
0               22542   17235
1               14050   10017
2                9107    5781
3                4924    3755
4                3950    5206
5                7137   23452
6               17589   72442
7               33327  145629
8               47003  177870
9               47865  111367
10              59280   95188
11              75960  111085
12              88531  125885
13              90188  123328
14              95040  125323
15             104610  159245
16             119370  228465
17             126358  258590
18             103819  191425
19              75011  129524
20              53654   88018
21              45324   67065
22              37823   47104
23              27693   28502

In [ ]:
#INSIGHTS
# 1. Members take more trips but casual riders take longer trips on average.
# 2. Casual riders ride significantly more on weekends, while Members ride more during weekdays.
# 3. Casual riders also take longer rides on weekends, while the average ride length for Members is consistent throughout the week.
# 4. Bike usage increase during the summer months for both Casual riders and Members.
# 5. Classic bikes are preferred over electric bikes by both Members and Casual riders.
# 6. Members ride more during commuting hours, while Casual riders ride more later during the day